import { OFFICIAL_ACCOUNT_NAME } from './site-profile.js';
// Reviewed sources: docs/planning/09-studio.md and studio-social-2026-10-07.md.
export const STUDIO_PLATFORMS = {
    knowledge: { label: '知识库', shape: 'tv' },
    skill: { label: 'Skill 与使用指南', shape: 'monitor' },
    wechat: { label: '微信文章', shape: 'phone' },
    xiaohongshu: { label: '小红书图文', shape: 'phone' },
    douyin: { label: '抖音视频', shape: 'phone' },
};

export const STUDIO_CONTENT = [{
    id: 'openclaw',
    title: 'OpenClaw 知识库',
    platform: 'knowledge',
    device: 'tv',
    screenTitle: 'OpenClaw\n知识库',
    screenCaption: '记忆 · 心跳 · Skills',
    status: '免费阅读',
    description: '从运行逻辑、记忆、心跳到 Skills，用易懂的方式理解和使用 OpenClaw。\n\n从《别让你的 OpenClaw，最后只用来问天气》开始，了解如何组织上下文、管理知识库，让它参与日常工作。',
    url: 'https://my.feishu.cn/wiki/Sd9qwSs6CiCidPkBniZcCWeOnDh',
    actionLabel: '打开知识库',
}, {
    id: 'shian-skill-hub',
    title: 'ShiAn Skill Hub',
    platform: 'skill',
    device: 'monitor',
    screenTitle: 'ShiAn\nSkill Hub',
    screenCaption: 'Skill 与使用指南',
    description: '分享可复用的 Skill 与使用指南。\n\n当前入口可以阅读《Simple Local Memory - 纯本地零依赖 AI 记忆系统使用指南》，了解本地记忆的分层组织、检索与日常维护。',
    url: 'https://my.feishu.cn/wiki/space/7622175237550918866?ccm_open_type=lark_wiki_spaceLink&open_tab_from=wiki_home',
    actionLabel: '打开知识库',
}, {
    id: 'jev',
    title: 'Jev 火了，一个不会聊天的模型，凭什么被开发者抢着用？',
    platform: 'wechat',
    device: 'phone',
    screenTitle: 'Jev 火了，\n一个不会聊天的模型',
    screenCaption: OFFICIAL_ACCOUNT_NAME,
    date: '2026-09-20',
    author: '时安不安',
    description: '从选择、打分和概率判断出发，聊聊 Jev 如何参与软件里的小决策，以及它的能力边界。\n\n当 AI 不再负责生成长篇回答，它还能怎样帮助开发者？',
    cover: '/images/studio/wechat-one.jpg',
    coverAlt: '文章《Jev 火了，一个不会聊天的模型，凭什么被开发者抢着用？》原始封面',
    url: 'https://mp.weixin.qq.com/s/ddydKmHXU_l8Z4u1RbNWdw',
    actionLabel: '阅读原文',
}, {
    id: 'deepseek-harness',
    title: '一切皆插件，DeepSeek 把 Agent 的底盘打开了',
    platform: 'wechat',
    device: 'monitor',
    screenTitle: '一切皆插件\nDeepSeek Harness',
    screenCaption: OFFICIAL_ACCOUNT_NAME,
    date: '2026-08-14',
    author: '时安不安',
    description: '从 DeepSeek Harness 的插件结构出发，拆解模型、工具、记忆和执行环境如何组成一个 Agent。\n\n聊聊这种设计怎样为个人和企业搭建专属 Agent 提供空间。',
    cover: '/images/studio/wechat-two.jpg',
    coverAlt: '文章《一切皆插件，DeepSeek 把 Agent 的底盘打开了》原始封面',
    url: 'https://mp.weixin.qq.com/s/21ooV0hGL6RyObA748M0fA',
    actionLabel: '阅读原文',
}, {
    id: 'crybaby',
    title: 'Crybaby哭娃 · 聆听每一份微小情绪',
    platform: 'xiaohongshu',
    device: 'phone',
    screenTitle: 'Crybaby哭娃\n微小情绪',
    screenCaption: '小红书 · 潮玩创作',
    date: '2026-07-30',
    author: '今天也在泡泡里',
    description: '围绕 Crybaby 接纳情绪的创作内核，用通勤、入梦、期待落空和居家时光等造型，表达日常里的喜怒哀乐。\n\nAI 二创，非官方商品，仅作个人创作分享。',
    cover: '/images/studio/crybaby.webp',
    coverAlt: 'Crybaby 哭娃笔记的原始封面',
    url: 'https://xhslink.cn/o/9gigzXJm7ux',
    actionLabel: '查看小红书笔记',
}, {
    id: 'dimoo',
    title: 'Dimoo系列 · 氛围感直接拉满',
    platform: 'xiaohongshu',
    device: 'phone',
    screenTitle: 'Dimoo系列\n四种氛围',
    screenCaption: '小红书 · 潮玩创作',
    date: '2026-06-16',
    author: '今天也在泡泡里',
    description: '四套不同氛围的 Dimoo 创作：幻夜志怪的古风意境、民俗小记的市井年味、晴空邮局的云端信使，以及夏夜萤火的林间晚风。\n\nAI 二创，非官方商品，仅作个人创作分享。',
    cover: '/images/studio/dimoo.webp',
    coverAlt: 'Dimoo 系列笔记的原始封面',
    url: 'https://xhslink.cn/o/LK9Un3aNg6',
    actionLabel: '查看小红书笔记',
}, {
    id: 'font-introduction',
    title: '写书法的人，可以把自己的字做成字库',
    platform: 'xiaohongshu',
    device: 'phone',
    screenTitle: '自己的字\n做成字库',
    screenCaption: '小红书 · 时安lab',
    date: '2026-09-22',
    author: '时安lab',
    description: '我开发的 Shian Font Workbench，可将方格纸手写稿导入、切分、去线，逐字核对和调整后导出 TTF 字体。\n\n识别仍需人工校对，字库只包含实际写过并确认的字；可以从常用字逐步积累，用于字帖、课件和教案。',
    cover: '/images/studio/font-introduction.webp',
    coverAlt: '书法字库工具介绍笔记的原始封面',
    url: 'https://xhslink.cn/o/6EOZqpKnZpC',
    actionLabel: '查看小红书笔记',
}, {
    id: 'font-workflow',
    title: '一张书法手写稿，怎么变成电脑字体？',
    platform: 'xiaohongshu',
    device: 'phone',
    screenTitle: '一张手写稿\n变成电脑字体',
    screenCaption: '小红书 · 时安lab',
    date: '2026-09-23',
    author: '时安lab',
    description: '把手写稿做成字体，再放进 WPS 里输入和排版，让纸上写下的字重新组成一行、一段，用于字帖和教学课件。\n\n识别错误要改，字的大小和位置也需要调整；先整理平时用得上的字，以后再慢慢补充，同时保留原来的书写味道。',
    cover: '/images/studio/font-workflow.webp',
    coverAlt: '手写稿转电脑字体笔记的原始封面',
    url: 'https://xhslink.cn/o/Amu0vdsG7U8',
    actionLabel: '查看小红书笔记',
}, {
    id: 'font-teaching',
    title: '做教材、排字帖，也能用上自己写的字',
    platform: 'douyin',
    device: 'phone',
    screenTitle: '做教材 · 排字帖\n用自己写的字',
    screenCaption: '抖音 · 时安不安',
    date: '2026-09-22',
    author: '时安不安',
    description: '用时安字库工作台，把手写稿整理成电脑字体，再在 WPS 里输入、调整字号、重新排版，让教材范字、课堂练习和课件示例保留自己的书写风格。\n\n这条视频展示从手写稿到电脑排版的过程。识别结果仍需要检查，可以从下节课要用的字开始逐步积累。',
    url: 'https://www.douyin.com/video/7688346313179858158',
    actionLabel: '观看抖音视频',
}, {
    id: 'font-applications',
    title: '手写字做成字体后，能用在哪里？',
    platform: 'douyin',
    device: 'phone',
    screenTitle: '手写字体\n能用在哪里？',
    screenCaption: '抖音 · 时安不安',
    author: '时安不安',
    description: '用“清、深、淡”三个字，展示手写字体的五种教学样张：教材内页、练习册、课堂课件、书法字帖专题页，以及书法机构的课程宣传页。\n\n练习册可以把范字调浅，留格描写和临写；字帖按专题集中范字，方便翻看对照；课件和宣传页则把字放大，作为画面的重点。',
    url: 'https://www.douyin.com/video/7688560225674713075',
    actionLabel: '观看抖音视频',
}];
